"""
Initial setup script for Creative Media Co-Pilot (Agentic AI)
Run this first to set up your environment
"""

import os
import sys
import subprocess


def print_header(text):
    """Print a formatted header"""
    print("\n" + "="*70)
    print(f"  {text}")
    print("="*70 + "\n")


def check_python_version():
    """Verify Python version is 3.8+"""
    print_header("Checking Python Version")
    
    version = sys.version_info
    print(f"Python version: {version.major}.{version.minor}.{version.micro}")
    
    


def install_dependencies():
    """Install required packages from requirements.txt"""
    print_header("Installing Dependencies")
    
    if not os.path.exists("requirements.txt"):
        print("❌ requirements.txt not found!")
        return False
    
    print("📦 Installing packages from requirements.txt...")
    print("   This may take a few minutes...\n")
    
    try:
        subprocess.check_call([
            sys.executable, "-m", "pip", "install", "-r", "requirements.txt"
        ])
        print("\n✅ All dependencies installed successfully!")
        return True
    except subprocess.CalledProcessError as e:
        print(f"\n❌ Failed to install dependencies: {e}")
        return False


def setup_env_file():
    """Guide user through .env file creation"""
    print_header("Setting Up Environment Variables")
    
    if os.path.exists(".env"):
        print("⚠️  .env file already exists")
        response = input("Do you want to recreate it? (y/n): ").strip().lower()
        if response != 'y':
            print("Skipping .env setup")
            return True
    
    print("\n📖 You'll need API keys from:")
    print("   • Groq: https://console.groq.com/keys")
    print("   • Together AI: https://api.together.ai/settings/api-keys")
    print("\n💡 Don't have API keys yet? You can set them up later.")
    
    setup_now = input("\nSet up API keys now? (y/n): ").strip().lower()
    
    if setup_now == 'y':
        groq_key = input("\nEnter your Groq API key (or press Enter to skip): ").strip()
        together_key = input("Enter your Together AI API key (or press Enter to skip): ").strip()
        
        if not groq_key:
            groq_key = "gsk_YOUR_GROQ_KEY_HERE"
        if not together_key:
            together_key = "YOUR_TOGETHER_KEY_HERE"
        
        env_content = f"""# API Keys for Creative Media Co-Pilot (Agentic AI)
# Generated by setup.py

# Groq API Key for Writer & Reviewer Agents (Llama 3 8B)
# Get yours at: https://console.groq.com/keys
GROQ_API_KEY={groq_key}

# Together AI API Key for Art Director Agent (FLUX.1-schnell)
# Get yours at: https://api.together.ai/settings/api-keys
TOGETHER_API_KEY={together_key}
"""
        
        with open(".env", "w") as f:
            f.write(env_content)
        
        print("✅ .env file created successfully!")
        
        if groq_key == "gsk_YOUR_GROQ_KEY_HERE" or together_key == "YOUR_TOGETHER_KEY_HERE":
            print("\n⚠️  Remember to update .env with your actual API keys before running!")
    else:
        # Copy .env.example to .env
        if os.path.exists(".env.example"):
            with open(".env.example", "r") as src:
                with open(".env", "w") as dst:
                    dst.write(src.read())
            print("✅ Created .env from .env.example")
            print("   → Edit .env and add your API keys before running")
    
    return True


def verify_installation():
    """Verify all packages are installed correctly"""
    print_header("Verifying Installation")
    
    required_packages = [
        "langgraph",
        "langchain",
        "langchain_groq",
        "langchain_together",
        "dotenv",
    ]
    
    all_good = True
    
    for package in required_packages:
        try:
            if package == "dotenv":
                __import__("dotenv")
            else:
                __import__(package)
            print(f"✅ {package}")
        except ImportError:
            print(f"❌ {package} - NOT INSTALLED")
            all_good = False
    
    if all_good:
        print("\n✅ All packages verified successfully!")
    else:
        print("\n⚠️  Some packages are missing. Try running setup again.")
    
    return all_good


def print_next_steps():
    """Print instructions for next steps"""
    print_header("Setup Complete! 🎉")
    
    print("Next steps:\n")
    print("1. 📝 Configure your API keys:")
    print("   → Edit the .env file with your Groq and Together AI keys")
    print()
    print("2. ✅ Validate your setup:")
    print("   → python utils.py check")
    print()
    print("3. 🚀 Run your first campaign:")
    print("   → python main.py")
    print()
    print("4. 📚 Learn more:")
    print("   → Check README.md for detailed documentation")
    print("   → Check ARCHITECTURE_VISUAL.md for system architecture")
    print("   → Check examples.py for sample campaigns")
    print()
    print("💡 Tips:")
    print("   • python utils.py diagram     - View system architecture")
    print("   • python examples.py list     - See example campaigns")
    print("   • python examples.py all      - Run all examples")
    print()


def main():
    """Main setup flow"""
    print("\n" + "="*70)
    print("  🤖 Creative Media Co-Pilot - Setup Wizard")
    print("="*70)
    print("\nThis script will set up your environment for the project.\n")
    
    # Step 1: Check Python version
    if not check_python_version():
        return False
    
    # Step 2: Install dependencies
    install_response = input("\n📦 Install Python dependencies? (y/n): ").strip().lower()
    if install_response == 'y':
        if not install_dependencies():
            return False
    else:
        print("⏭️  Skipping dependency installation")
    
    # Step 3: Verify installation
    if install_response == 'y':
        if not verify_installation():
            print("\n⚠️  Setup incomplete. Please check the errors above.")
            return False
    
    # Step 4: Set up .env file
    env_response = input("\n🔑 Set up API keys? (y/n): ").strip().lower()
    if env_response == 'y':
        if not setup_env_file():
            return False
    else:
        print("⏭️  Skipping API key setup (you can do this later with: python utils.py create-env)")
    
    # Step 5: Print next steps
    print_next_steps()
    
    return True


if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Setup failed with error: {e}")
        sys.exit(1)
